DROP TABLE IF EXISTS User;
DROP TABLE IF EXISTS Event; 
DROP TABLE IF EXISTS EventType;
DROP TABLE IF EXISTS Comment;
DROP TABLE IF EXISTS AdminEvent;
DROP TABLE IF EXISTS GoToEvent;


CREATE TABLE User(
idUser INTEGER PRIMARY KEY,
user VARCHAR NOT NULL,
password VARCHAR NOT NULL
);

CREATE TABLE Event(
idEvent INTEGER PRIMARY KEY,
title VARCHAR NOT NULL,
datadoEvento DATE,
descricao VARCHAR NOT NULL,
image VARCHAR NOT NULL,
idEventType INTEGER REFERENCES EventType(idEventType);
);

CREATE TABLE EventType(
idEventType INTEGER PRIMARY KEY,
type VARCHAR NOT NULL
);

CREATE TABLE AdminEvent(
 idUser INTEGER REFERENCES User(idUser),
 idEvent INTEGER REFERENCES Event(idEvent),
 PRIMARY KEY(idUser,idEvent)
);

CREATE TABLE GoToEvent(
 idUser INTEGER REFERENCES User(idUser),
 idEvent INTEGER REFERENCES Event(idEvent),
 PRIMARY KEY(idUser,idEvent)
);

CREATE TABLE Comment(
	idComment INTEGER PRIMARY KEY,
	idUser INTEGER REFERENCES User(idUser),
	idEvent INTEGER REFERENCES Event(idEvent),
	comentario VARCHAR NOT NULL
);



